spring:
  datasource:
    username: wedding_rsvp
    password: wedding_rsvp
    url: jdbc:mysql://localhost:3306/wedding_rsvp
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  sql:
    init:
      mode: always
      